setCpm(120/4)

const dbank = "tr909"
$: sound("bd(<5 7>,16)")
  .bank(dbank)
  ._punchcard()

$: sound("sd")
  .beat("4,12", 16)
  .bank(dbank)
  ._punchcard()

$: sound("hh!8")
  .n("[0 | 1]*8")
  .sometimesBy(.2, x=>x.ply("2"))
  .gain(.4)
  ._punchcard()

let chords = chord("<Bbm9 Fm9>/4").dict('ireal')
$: chords.n("[0 <4 3 <2 5>>*2](<3 5>,8)")
  .sound("sawtooth")
  .anchor("D5")
  .voicing()
  .segment(8)
  .room(.1)
  .delay(.1)
  .release(.05)
  .distort(.4)
  .unison(4)
  .lpf(8000)
  .hpf(300)
  .penv(0.1)
  .postgain(1)
  .fast(2)
  ._punchcard()
